seed_everything: 0
data:
  class_path: data_modules.CombinedDataModule
  init_args:
    batch_size: 4
    num_workers: 4
    load_config:
      train:
        Cityscapes:
          rcs_enabled: True
          dims:
            - 512
            - 1024
          load_keys:
            - image
            - semantic
            - image_enhance
            - semantic_enhance
          transforms:
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.RandomCrop
              init_args:
                size: 
                  - 512
                  - 512
                cat_max_ratio: 0.75
            - class_path: data_modules.transforms.ColorJitter
              init_args:
                apply_keys:
                  - image_enhance
                  - semantic_enhance
                brightness: 0.6
                contrast: 0.6
                saturation: 0.6
                hue: 0
            - class_path: data_modules.transforms.RandomGaussianBlur
              init_args:
                apply_keys:
                  - image_enhance
                  - semantic_enhance
                p: 0.2
                kernel_size: 7
                sigma:
                  - 0.2
                  - 2.0
            - class_path: data_modules.transforms.RandomHorizontalFlip
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
            - class_path: data_modules.transforms.CompositeFlow
              init_args:
                apply_keys:
                  - image_enhance
                  - semantic_enhance
                include_transforms:
                  - hom
                  - tps
                  - afftps
                random_alpha: 0.26
                random_s: 0.45
                random_tx: 0.25
                random_ty: 0.25
                random_t_hom: 0.333
                random_t_tps: 0.333
                random_t_tps_for_afftps: 0.08
                parameterize_with_gaussian: False
                add_elastic: False
        DarkZurich:
          dims:
            - 540
            - 960
          load_keys:
            - image
            - image_ref
          transforms:
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.RandomCrop
              init_args:
                size: 
                  - 512
                  - 512
            - class_path: data_modules.transforms.RandomHorizontalFlip
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
      val:
        DarkZurich:
          dims:
            - 540
            - 960
          load_keys:
            - image
            - semantic
          transforms:
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
      test:
        DarkZurich:
          load_keys:
            - image
            - semantic
          transforms:
            - class_path: data_modules.transforms.Resize
              init_args:
                size:
                  - 540
                  - 960
                img_only: True
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
        NighttimeDriving:
          load_keys:
            - image
            - semantic
          transforms:
            - class_path: data_modules.transforms.Resize
              init_args:
                size:
                  - 540
                  - 960
                img_only: True
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
        BDD100kNight:
          load_keys:
            - image
            - semantic
          transforms:
            - class_path: data_modules.transforms.Resize
              init_args:
                size:
                  - 540
                  - 960
                img_only: True
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
      predict:
        DarkZurich:
          predict_on: test
          load_keys:
            - image
          transforms:
            - class_path: data_modules.transforms.Resize
              init_args:
                size:
                  - 540
                  - 960
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
model:
  class_path: models.DomainAdaptationSegmentationModel
  init_args:
    backbone_lr_factor: 0.1
    dar_lr_factor: 0.1
    psweight_ignore_top: 15
    psweight_ignore_bottom: 15
    enable_fdist: True
    use_ref: True
    adapt_to_ref: True
    gamma: 0.25
    backbone:
      class_path: models.backbones.MixVisionTransformer
      init_args:
        model_type: mit_b5
        pretrained: imagenet
    head:
      class_path: models.heads.DAFormerHead
      init_args:
        in_channels:
          - 64
          - 128
          - 320
          - 512
        in_index:
          - 0
          - 1
          - 2
          - 3
        num_classes: 19
        input_transform: multiple_select
    dat:
      class_path: models.DAT.DAT
      init_args:
        model_type: dat_tiny
    prototype:
      class_path: models.prototype.Prototype
      init_args:
        class_num: 19
        feature_num: 19
        use_momentum: True
        momentum: 0.9
    loss:
      class_path: models.losses.PixelWeightedCrossEntropyLoss
    pcl:
      class_path: models.prototype.PrototypeContrastiveLoss
    metrics:
      val:
        DarkZurich:
          - class_path: helpers.metrics.IoU
            init_args:
              ignore_index: 255
              num_classes: 19
              compute_on_step: False
      test:
        DarkZurich:
          - class_path: helpers.metrics.IoU
            init_args:
              ignore_index: 255
              num_classes: 19
              compute_on_step: False
        NighttimeDriving:
          - class_path: helpers.metrics.IoU
            init_args:
              ignore_index: 255
              num_classes: 19
              compute_on_step: False
        BDD100kNight:
          - class_path: helpers.metrics.IoU
            init_args:
              ignore_index: 255
              num_classes: 19
              compute_on_step: False
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0006
    weight_decay: 0.01
lr_scheduler:
  class_path: helpers.lr_scheduler.LinearWarmupPolynomialLR
  init_args:
    warmup_iters: 1500
    warmup_ratio: 0.000001
    power: 1.0
    max_steps: 40000
trainer:
  max_steps: 40001
  check_val_every_n_epoch: 40000
  sync_batchnorm: True
  multiple_trainloader_mode: min_size
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      name: refign_daformer_darkzurich
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: helpers.callbacks.ValEveryNSteps
      init_args:
        every_n_steps: 2000
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_DarkZurich_IoU
        save_top_k: 1
        save_last: True
        mode: max


